DATA SEGMENT PARA PUBLIC 'DATA'
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
START PROC FAR
ASSUME CS:CODE, DS:DATA 
	PUSH DS
	XOR AX,AX
	PUSH AX
	MOV AX,DATA
	MOV DS,AX
	
	MOV AX,12
    MOV BX,15
    MOV CX,10
    MOV DX,20
    MOV [BP+6],AX
    MOV [BP+4],BX
    MOV [BP+2],CX
    MOV [BP+0],DX
    MOV SP,[BP+0]
    MOV AX,SP
    MOV SP,[BP+2]
    MOV BX,SP
	RET
START ENDP
CODE ENDS
END START